//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="urn:wservicewsdl", ConfigurationName="wservicePortType")]
public interface wservicePortType
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#timbrar", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string timbrar(string rfc, string clave, string xml, string produccion);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#timbrar", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> timbrarAsync(string rfc, string clave, string xml, string produccion);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#timbrar", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    RespuestaNET timbrarNET(string rfc, string clave, string xml, string produccion);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#timbrar", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<RespuestaNET> timbrarNETAsync(string rfc, string clave, string xml, string produccion);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#timbrar64", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string timbrar64(string rfc, string clave, string xml, string produccion);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#timbrar64", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> timbrar64Async(string rfc, string clave, string xml, string produccion);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#timbrar", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string retencion(string rfc, string clave, string xml, string produccion);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#timbrar", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> retencionAsync(string rfc, string clave, string xml, string produccion);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#saldo", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string saldo(string rfc, string clave);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#saldo", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> saldoAsync(string rfc, string clave);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#saldoNET", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    saldoResponse saldoNET(string rfc, string clave);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#saldoNET", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<saldoResponse> saldoNETAsync(string rfc, string clave);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#cancelar", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string cancelar(string rfc, string clave, string uuid, string cer, string key, string pass_cer);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#cancelar", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> cancelarAsync(string rfc, string clave, string uuid, string cer, string key, string pass_cer);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#generar_pem", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string generar_pem(string cer_base64, string key_base64, string pass_base64);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#generar_pem", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> generar_pemAsync(string cer_base64, string key_base64, string pass_base64);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#ticket", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string respaldo_masivo(string rfc, string clave, string respaldo_base64);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#ticket", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> respaldo_masivoAsync(string rfc, string clave, string respaldo_base64);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#ticket", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string ticket(string rfc, string clave, [System.ServiceModel.MessageParameterAttribute(Name="ticket")] string ticket1, string produccion);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#ticket", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> ticketAsync(string rfc, string clave, string ticket, string produccion);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#ticket_reporte", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string ticket_reporte(string rfc, string clave, string tipo, string fecha_inicial, string fecha_final);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#ticket_reporte", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> ticket_reporteAsync(string rfc, string clave, string tipo, string fecha_inicial, string fecha_final);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#ticket_reporte", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string ticket_cancela(string rfc, string clave, string codigo);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#ticket_reporte", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> ticket_cancelaAsync(string rfc, string clave, string codigo);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#factura_reporte", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string factura_reporte(string rfc, string clave, string mes, string ano);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#factura_reporte", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> factura_reporteAsync(string rfc, string clave, string mes, string ano);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#factura_respaldo", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string factura_recupera_respaldo(string rfc, string clave, string referencia, string uuid);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#factura_respaldo", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> factura_recupera_respaldoAsync(string rfc, string clave, string referencia, string uuid);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#genera_dotnet", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string genera_dotnet(string empresa, string pwd, string fe_xml);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#genera_dotnet", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> genera_dotnetAsync(string empresa, string pwd, string fe_xml);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#genera_ut8", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string genera_ut8(string rfc, string clave, string xml);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#genera_ut8", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> genera_ut8Async(string rfc, string clave, string xml);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#acuseSAT", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string acuseSAT(string rfc, string pwd, string uuid);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#acuseSAT", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> acuseSATAsync(string rfc, string pwd, string uuid);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#cancela_ut8", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string cancela_ut8(string rfc, string pwd, string xml_in);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#cancela_ut8", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> cancela_ut8Async(string rfc, string pwd, string xml_in);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#timbradoMicrosip", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string timbradoMICROSIP(string rfc, string clave, string tipo, string xml, string produccion);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#timbradoMicrosip", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> timbradoMICROSIPAsync(string rfc, string clave, string tipo, string xml, string produccion);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#timbrar33b64", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    RespuestaNET timbrar33b64(string rfc, string clave, string xml, string produccion);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:wservicewsdl#timbrar33b64", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<RespuestaNET> timbrar33b64Async(string rfc, string clave, string xml, string produccion);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:wservicewsdl")]
public partial class RespuestaNET
{
    
    private string cfdiField;
    
    private string pngField;
    
    private int idpacField;
    
    private int pacField;
    
    private string produccionField;
    
    private int codigo_mf_numeroField;
    
    private string codigo_mf_textoField;
    
    private string mensaje_original_pac_jsonField;
    
    private string canceladaField;
    
    private int saldoField;
    
    private string uuidField;
    
    private string servidorField;
    
    private float ejecucionField;
    
    private string debugField;
    
    /// <remarks/>
    public string cfdi
    {
        get
        {
            return this.cfdiField;
        }
        set
        {
            this.cfdiField = value;
        }
    }
    
    /// <remarks/>
    public string png
    {
        get
        {
            return this.pngField;
        }
        set
        {
            this.pngField = value;
        }
    }
    
    /// <remarks/>
    public int idpac
    {
        get
        {
            return this.idpacField;
        }
        set
        {
            this.idpacField = value;
        }
    }
    
    /// <remarks/>
    public int pac
    {
        get
        {
            return this.pacField;
        }
        set
        {
            this.pacField = value;
        }
    }
    
    /// <remarks/>
    public string produccion
    {
        get
        {
            return this.produccionField;
        }
        set
        {
            this.produccionField = value;
        }
    }
    
    /// <remarks/>
    public int codigo_mf_numero
    {
        get
        {
            return this.codigo_mf_numeroField;
        }
        set
        {
            this.codigo_mf_numeroField = value;
        }
    }
    
    /// <remarks/>
    public string codigo_mf_texto
    {
        get
        {
            return this.codigo_mf_textoField;
        }
        set
        {
            this.codigo_mf_textoField = value;
        }
    }
    
    /// <remarks/>
    public string mensaje_original_pac_json
    {
        get
        {
            return this.mensaje_original_pac_jsonField;
        }
        set
        {
            this.mensaje_original_pac_jsonField = value;
        }
    }
    
    /// <remarks/>
    public string cancelada
    {
        get
        {
            return this.canceladaField;
        }
        set
        {
            this.canceladaField = value;
        }
    }
    
    /// <remarks/>
    public int saldo
    {
        get
        {
            return this.saldoField;
        }
        set
        {
            this.saldoField = value;
        }
    }
    
    /// <remarks/>
    public string uuid
    {
        get
        {
            return this.uuidField;
        }
        set
        {
            this.uuidField = value;
        }
    }
    
    /// <remarks/>
    public string servidor
    {
        get
        {
            return this.servidorField;
        }
        set
        {
            this.servidorField = value;
        }
    }
    
    /// <remarks/>
    public float ejecucion
    {
        get
        {
            return this.ejecucionField;
        }
        set
        {
            this.ejecucionField = value;
        }
    }
    
    /// <remarks/>
    public string debug
    {
        get
        {
            return this.debugField;
        }
        set
        {
            this.debugField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:wservicewsdl")]
public partial class saldoResponse
{
    
    private string saldoResultField;
    
    private int saldoField;
    
    /// <remarks/>
    public string saldoResult
    {
        get
        {
            return this.saldoResultField;
        }
        set
        {
            this.saldoResultField = value;
        }
    }
    
    /// <remarks/>
    public int saldo
    {
        get
        {
            return this.saldoField;
        }
        set
        {
            this.saldoField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface wservicePortTypeChannel : wservicePortType, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class wservicePortTypeClient : System.ServiceModel.ClientBase<wservicePortType>, wservicePortType
{
    
    public wservicePortTypeClient()
    {
    }
    
    public wservicePortTypeClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public wservicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public wservicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public wservicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string timbrar(string rfc, string clave, string xml, string produccion)
    {
        return base.Channel.timbrar(rfc, clave, xml, produccion);
    }
    
    public System.Threading.Tasks.Task<string> timbrarAsync(string rfc, string clave, string xml, string produccion)
    {
        return base.Channel.timbrarAsync(rfc, clave, xml, produccion);
    }
    
    public RespuestaNET timbrarNET(string rfc, string clave, string xml, string produccion)
    {
        return base.Channel.timbrarNET(rfc, clave, xml, produccion);
    }
    
    public System.Threading.Tasks.Task<RespuestaNET> timbrarNETAsync(string rfc, string clave, string xml, string produccion)
    {
        return base.Channel.timbrarNETAsync(rfc, clave, xml, produccion);
    }
    
    public string timbrar64(string rfc, string clave, string xml, string produccion)
    {
        return base.Channel.timbrar64(rfc, clave, xml, produccion);
    }
    
    public System.Threading.Tasks.Task<string> timbrar64Async(string rfc, string clave, string xml, string produccion)
    {
        return base.Channel.timbrar64Async(rfc, clave, xml, produccion);
    }
    
    public string retencion(string rfc, string clave, string xml, string produccion)
    {
        return base.Channel.retencion(rfc, clave, xml, produccion);
    }
    
    public System.Threading.Tasks.Task<string> retencionAsync(string rfc, string clave, string xml, string produccion)
    {
        return base.Channel.retencionAsync(rfc, clave, xml, produccion);
    }
    
    public string saldo(string rfc, string clave)
    {
        return base.Channel.saldo(rfc, clave);
    }
    
    public System.Threading.Tasks.Task<string> saldoAsync(string rfc, string clave)
    {
        return base.Channel.saldoAsync(rfc, clave);
    }
    
    public saldoResponse saldoNET(string rfc, string clave)
    {
        return base.Channel.saldoNET(rfc, clave);
    }
    
    public System.Threading.Tasks.Task<saldoResponse> saldoNETAsync(string rfc, string clave)
    {
        return base.Channel.saldoNETAsync(rfc, clave);
    }
    
    public string cancelar(string rfc, string clave, string uuid, string cer, string key, string pass_cer)
    {
        return base.Channel.cancelar(rfc, clave, uuid, cer, key, pass_cer);
    }
    
    public System.Threading.Tasks.Task<string> cancelarAsync(string rfc, string clave, string uuid, string cer, string key, string pass_cer)
    {
        return base.Channel.cancelarAsync(rfc, clave, uuid, cer, key, pass_cer);
    }
    
    public string generar_pem(string cer_base64, string key_base64, string pass_base64)
    {
        return base.Channel.generar_pem(cer_base64, key_base64, pass_base64);
    }
    
    public System.Threading.Tasks.Task<string> generar_pemAsync(string cer_base64, string key_base64, string pass_base64)
    {
        return base.Channel.generar_pemAsync(cer_base64, key_base64, pass_base64);
    }
    
    public string respaldo_masivo(string rfc, string clave, string respaldo_base64)
    {
        return base.Channel.respaldo_masivo(rfc, clave, respaldo_base64);
    }
    
    public System.Threading.Tasks.Task<string> respaldo_masivoAsync(string rfc, string clave, string respaldo_base64)
    {
        return base.Channel.respaldo_masivoAsync(rfc, clave, respaldo_base64);
    }
    
    public string ticket(string rfc, string clave, string ticket1, string produccion)
    {
        return base.Channel.ticket(rfc, clave, ticket1, produccion);
    }
    
    public System.Threading.Tasks.Task<string> ticketAsync(string rfc, string clave, string ticket, string produccion)
    {
        return base.Channel.ticketAsync(rfc, clave, ticket, produccion);
    }
    
    public string ticket_reporte(string rfc, string clave, string tipo, string fecha_inicial, string fecha_final)
    {
        return base.Channel.ticket_reporte(rfc, clave, tipo, fecha_inicial, fecha_final);
    }
    
    public System.Threading.Tasks.Task<string> ticket_reporteAsync(string rfc, string clave, string tipo, string fecha_inicial, string fecha_final)
    {
        return base.Channel.ticket_reporteAsync(rfc, clave, tipo, fecha_inicial, fecha_final);
    }
    
    public string ticket_cancela(string rfc, string clave, string codigo)
    {
        return base.Channel.ticket_cancela(rfc, clave, codigo);
    }
    
    public System.Threading.Tasks.Task<string> ticket_cancelaAsync(string rfc, string clave, string codigo)
    {
        return base.Channel.ticket_cancelaAsync(rfc, clave, codigo);
    }
    
    public string factura_reporte(string rfc, string clave, string mes, string ano)
    {
        return base.Channel.factura_reporte(rfc, clave, mes, ano);
    }
    
    public System.Threading.Tasks.Task<string> factura_reporteAsync(string rfc, string clave, string mes, string ano)
    {
        return base.Channel.factura_reporteAsync(rfc, clave, mes, ano);
    }
    
    public string factura_recupera_respaldo(string rfc, string clave, string referencia, string uuid)
    {
        return base.Channel.factura_recupera_respaldo(rfc, clave, referencia, uuid);
    }
    
    public System.Threading.Tasks.Task<string> factura_recupera_respaldoAsync(string rfc, string clave, string referencia, string uuid)
    {
        return base.Channel.factura_recupera_respaldoAsync(rfc, clave, referencia, uuid);
    }
    
    public string genera_dotnet(string empresa, string pwd, string fe_xml)
    {
        return base.Channel.genera_dotnet(empresa, pwd, fe_xml);
    }
    
    public System.Threading.Tasks.Task<string> genera_dotnetAsync(string empresa, string pwd, string fe_xml)
    {
        return base.Channel.genera_dotnetAsync(empresa, pwd, fe_xml);
    }
    
    public string genera_ut8(string rfc, string clave, string xml)
    {
        return base.Channel.genera_ut8(rfc, clave, xml);
    }
    
    public System.Threading.Tasks.Task<string> genera_ut8Async(string rfc, string clave, string xml)
    {
        return base.Channel.genera_ut8Async(rfc, clave, xml);
    }
    
    public string acuseSAT(string rfc, string pwd, string uuid)
    {
        return base.Channel.acuseSAT(rfc, pwd, uuid);
    }
    
    public System.Threading.Tasks.Task<string> acuseSATAsync(string rfc, string pwd, string uuid)
    {
        return base.Channel.acuseSATAsync(rfc, pwd, uuid);
    }
    
    public string cancela_ut8(string rfc, string pwd, string xml_in)
    {
        return base.Channel.cancela_ut8(rfc, pwd, xml_in);
    }
    
    public System.Threading.Tasks.Task<string> cancela_ut8Async(string rfc, string pwd, string xml_in)
    {
        return base.Channel.cancela_ut8Async(rfc, pwd, xml_in);
    }
    
    public string timbradoMICROSIP(string rfc, string clave, string tipo, string xml, string produccion)
    {
        return base.Channel.timbradoMICROSIP(rfc, clave, tipo, xml, produccion);
    }
    
    public System.Threading.Tasks.Task<string> timbradoMICROSIPAsync(string rfc, string clave, string tipo, string xml, string produccion)
    {
        return base.Channel.timbradoMICROSIPAsync(rfc, clave, tipo, xml, produccion);
    }
    
    public RespuestaNET timbrar33b64(string rfc, string clave, string xml, string produccion)
    {
        return base.Channel.timbrar33b64(rfc, clave, xml, produccion);
    }
    
    public System.Threading.Tasks.Task<RespuestaNET> timbrar33b64Async(string rfc, string clave, string xml, string produccion)
    {
        return base.Channel.timbrar33b64Async(rfc, clave, xml, produccion);
    }
}
