//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Essentials {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Business.Essentials.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información del Usuario.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Cuenta.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramos Ferretería.
        /// </summary>
        public static string Alt_Logo {
            get {
                return ResourceManager.GetString("Alt_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autores.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Banco.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumpleaños.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegación o Municipio.
        /// </summary>
        public static string Borough {
            get {
                return ResourceManager.GetString("Borough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelado.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar Orden.
        /// </summary>
        public static string CancelOrder {
            get {
                return ResourceManager.GetString("CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efectivo.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caja.
        /// </summary>
        public static string CashDrawer {
            get {
                return ResourceManager.GetString("CashDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cajero.
        /// </summary>
        public static string Cashier {
            get {
                return ResourceManager.GetString("Cashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesión de Caja.
        /// </summary>
        public static string CashSession {
            get {
                return ResourceManager.GetString("CashSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Línea de Producto.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Contraseña.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesión.
        /// </summary>
        public static string CloseSession {
            get {
                return ResourceManager.GetString("CloseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagado.
        /// </summary>
        public static string CompletePayment {
            get {
                return ResourceManager.GetString("CompletePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar Venta.
        /// </summary>
        public static string CompleteSale {
            get {
                return ResourceManager.GetString("CompleteSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Contraseña.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Nuevo.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crédito.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjeta de Crédito.
        /// </summary>
        public static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días de Crédito.
        /// </summary>
        public static string CreditDays {
            get {
                return ResourceManager.GetString("CreditDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Límite de Crédito.
        /// </summary>
        public static string CreditLimit {
            get {
                return ResourceManager.GetString("CreditLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña Actual.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y Hora.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjeta de Débito.
        /// </summary>
        public static string DebitCard {
            get {
                return ResourceManager.GetString("DebitCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denominación.
        /// </summary>
        public static string Denomination {
            get {
                return ResourceManager.GetString("Denomination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuento.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direcciones.
        /// </summary>
        public static string DisplayName_Addresses {
            get {
                return ResourceManager.GetString("DisplayName_Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bancos.
        /// </summary>
        public static string DisplayName_BankAccounts {
            get {
                return ResourceManager.GetString("DisplayName_BankAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Cajas.
        /// </summary>
        public static string DisplayName_CashDrawers {
            get {
                return ResourceManager.GetString("DisplayName_CashDrawers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesión de la Caja.
        /// </summary>
        public static string DisplayName_CashSession {
            get {
                return ResourceManager.GetString("DisplayName_CashSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Líneas de Producto.
        /// </summary>
        public static string DisplayName_Categories {
            get {
                return ResourceManager.GetString("DisplayName_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de Contraseña.
        /// </summary>
        public static string DisplayName_ChangePassword {
            get {
                return ResourceManager.GetString("DisplayName_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre de Sesión.
        /// </summary>
        public static string DisplayName_CloseSession {
            get {
                return ResourceManager.GetString("DisplayName_CloseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactos.
        /// </summary>
        public static string DisplayName_Contacts {
            get {
                return ResourceManager.GetString("DisplayName_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caja de Cobro.
        /// </summary>
        public static string DisplayName_CustomerPayments {
            get {
                return ResourceManager.GetString("DisplayName_CustomerPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Clientes.
        /// </summary>
        public static string DisplayName_Customers {
            get {
                return ResourceManager.GetString("DisplayName_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Venta.
        /// </summary>
        public static string DisplayName_EditSale {
            get {
                return ResourceManager.GetString("DisplayName_EditSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Empleados.
        /// </summary>
        public static string DisplayName_Employees {
            get {
                return ResourceManager.GetString("DisplayName_Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de Sesión.
        /// </summary>
        public static string DisplayName_LogOn {
            get {
                return ResourceManager.GetString("DisplayName_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta Nueva.
        /// </summary>
        public static string DisplayName_NewSale {
            get {
                return ResourceManager.GetString("DisplayName_NewSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Puntos de Venta.
        /// </summary>
        public static string DisplayName_PointsOfSale {
            get {
                return ResourceManager.GetString("DisplayName_PointsOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listas de Precios.
        /// </summary>
        public static string DisplayName_PriceLists {
            get {
                return ResourceManager.GetString("DisplayName_PriceLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Productos.
        /// </summary>
        public static string DisplayName_Products {
            get {
                return ResourceManager.GetString("DisplayName_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Usuario.
        /// </summary>
        public static string DisplayName_Register {
            get {
                return ResourceManager.GetString("DisplayName_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información de la Venta.
        /// </summary>
        public static string DisplayName_SalesInformation {
            get {
                return ResourceManager.GetString("DisplayName_SalesInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de la Venta.
        /// </summary>
        public static string DisplayName_SalesOrderDetails {
            get {
                return ResourceManager.GetString("DisplayName_SalesOrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto de Venta.
        /// </summary>
        public static string DisplayName_SalesOrders {
            get {
                return ResourceManager.GetString("DisplayName_SalesOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuerdos con Proveedor.
        /// </summary>
        public static string DisplayName_SupplierAgreements {
            get {
                return ResourceManager.GetString("DisplayName_SupplierAgreements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Proveedores.
        /// </summary>
        public static string DisplayName_Suppliers {
            get {
                return ResourceManager.GetString("DisplayName_Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Usuarios.
        /// </summary>
        public static string DisplayName_Users {
            get {
                return ResourceManager.GetString("DisplayName_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Almacenes.
        /// </summary>
        public static string DisplayName_Warehouses {
            get {
                return ResourceManager.GetString("DisplayName_Warehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Vencimiento.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Fin.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Exterior.
        /// </summary>
        public static string ExteriorNumber {
            get {
                return ResourceManager.GetString("ExteriorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femenino.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  FONACOT.
        /// </summary>
        public static string GovernmentFunding {
            get {
                return ResourceManager.GetString("GovernmentFunding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen de Ganancia Alto.
        /// </summary>
        public static string HighProfitMargin {
            get {
                return ResourceManager.GetString("HighProfitMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca lo que desea buscar..
        /// </summary>
        public static string HIntText {
            get {
                return ResourceManager.GetString("HIntText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección IP.
        /// </summary>
        public static string HostAddress {
            get {
                return ResourceManager.GetString("HostAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensajero.
        /// </summary>
        public static string Im {
            get {
                return ResourceManager.GetString("Im", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Interior.
        /// </summary>
        public static string InteriorNumber {
            get {
                return ResourceManager.GetString("InteriorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caja Inválido.
        /// </summary>
        public static string InvalidCashDrawer {
            get {
                return ResourceManager.GetString("InvalidCashDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto de Venta Inválido.
        /// </summary>
        public static string InvalidPointOfSale {
            get {
                return ResourceManager.GetString("InvalidPointOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturable.
        /// </summary>
        public static string Invoiceable {
            get {
                return ResourceManager.GetString("Invoiceable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puesto.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen de Ganancia Bajo.
        /// </summary>
        public static string LowProfitMargin {
            get {
                return ResourceManager.GetString("LowProfitMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cambio de contraseña no fue exitoso. Por favor, corrija los errores y vuelva a intentarlo..
        /// </summary>
        public static string Message_ChangePasswordFail {
            get {
                return ResourceManager.GetString("Message_ChangePasswordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su contraseña se ha cambiado exitosamente..
        /// </summary>
        public static string Message_ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("Message_ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña actual es incorrecta o la contraseña nueva es inválida..
        /// </summary>
        public static string Message_ChangePasswordWrong {
            get {
                return ResourceManager.GetString("Message_ChangePasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de borrar esto?.
        /// </summary>
        public static string Message_DeleteConfirmation {
            get {
                return ResourceManager.GetString("Message_DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo borrar el elemento porque existen dependencias en el sistema hacia él..
        /// </summary>
        public static string Message_DeleteUnsuccessful {
            get {
                return ResourceManager.GetString("Message_DeleteUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La máquina de la cuál se hizo la solicitud de cobro no está registrada como una caja válida..
        /// </summary>
        public static string Message_InvalidCashDrawer {
            get {
                return ResourceManager.GetString("Message_InvalidCashDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La máquina de la cuál se hizo la solicitud de venta no está registrada como un punto de venta válido..
        /// </summary>
        public static string Message_InvalidPointOfSale {
            get {
                return ResourceManager.GetString("Message_InvalidPointOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario o contraseña es  incorrecto..
        /// </summary>
        public static string Message_InvalidUserPassword {
            get {
                return ResourceManager.GetString("Message_InvalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese su usuario y contraseña. O si usted no tiene un usuario, favor de.
        /// </summary>
        public static string Message_LoginRegister {
            get {
                return ResourceManager.GetString("Message_LoginRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El inicio de sesión no fue exitoso. Por favor, corrija los errores y vuelva a intentarlo..
        /// </summary>
        public static string Message_LoginUnsuccessful {
            get {
                return ResourceManager.GetString("Message_LoginUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro no fue exitoso. Por favor, corrija los errores y vuelva a intentarlo..
        /// </summary>
        public static string Message_RegisterUnsuccessful {
            get {
                return ResourceManager.GetString("Message_RegisterUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error desconocido. Por favor, verifica tus datos y vuelve a intentarlo. Si el problema persiste contacte a su administrador de sistema..
        /// </summary>
        public static string Message_UnknownError {
            get {
                return ResourceManager.GetString("Message_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario ya existe..
        /// </summary>
        public static string Message_UserNameAlreadyExists {
            get {
                return ResourceManager.GetString("Message_UserNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método de Pago.
        /// </summary>
        public static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonia.
        /// </summary>
        public static string Neighborhood {
            get {
                return ResourceManager.GetString("Neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña Nueva.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta Nueva.
        /// </summary>
        public static string NewSale {
            get {
                return ResourceManager.GetString("NewSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nínguno.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe coincidencia..
        /// </summary>
        public static string NoResultsText {
            get {
                return ResourceManager.GetString("NoResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagado.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrón de Búsqueda.
        /// </summary>
        public static string Pattern {
            get {
                return ResourceManager.GetString("Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagar.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perecedero.
        /// </summary>
        public static string Perishable {
            get {
                return ResourceManager.GetString("Perishable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURP.
        /// </summary>
        public static string PersonalId {
            get {
                return ResourceManager.GetString("PersonalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensión Telefónica.
        /// </summary>
        public static string PhoneExt {
            get {
                return ResourceManager.GetString("PhoneExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto de Venta.
        /// </summary>
        public static string PointOfSale {
            get {
                return ResourceManager.GetString("PointOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrador.
        /// </summary>
        public static string Price1 {
            get {
                return ResourceManager.GetString("Price1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supermostrador.
        /// </summary>
        public static string Price2 {
            get {
                return ResourceManager.GetString("Price2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayoreo.
        /// </summary>
        public static string Price3 {
            get {
                return ResourceManager.GetString("Price3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especial.
        /// </summary>
        public static string Price4 {
            get {
                return ResourceManager.GetString("Price4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio x Kg.
        /// </summary>
        public static string Price5 {
            get {
                return ResourceManager.GetString("Price5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio x Mts.
        /// </summary>
        public static string Price6 {
            get {
                return ResourceManager.GetString("Price6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio x Pieza.
        /// </summary>
        public static string Price7 {
            get {
                return ResourceManager.GetString("Price7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Precios.
        /// </summary>
        public static string PriceList {
            get {
                return ResourceManager.GetString("PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precios.
        /// </summary>
        public static string Prices {
            get {
                return ResourceManager.GetString("Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Producto.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencia.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Recordarme?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clabe Interbancaria.
        /// </summary>
        public static string RoutingNumber {
            get {
                return ResourceManager.GetString("RoutingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden de Venta.
        /// </summary>
        public static string SalesOrder {
            get {
                return ResourceManager.GetString("SalesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio.
        /// </summary>
        public static string SalesOrderId {
            get {
                return ResourceManager.GetString("SalesOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendedor.
        /// </summary>
        public static string SalesPerson {
            get {
                return ResourceManager.GetString("SalesPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totales.
        /// </summary>
        public static string SalesTotals {
            get {
                return ResourceManager.GetString("SalesTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscando....
        /// </summary>
        public static string SearchingText {
            get {
                return ResourceManager.GetString("SearchingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seriable.
        /// </summary>
        public static string Seriable {
            get {
                return ResourceManager.GetString("Seriable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceder.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videoconferencia.
        /// </summary>
        public static string Sip {
            get {
                return ResourceManager.GetString("Sip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave.
        /// </summary>
        public static string SKU {
            get {
                return ResourceManager.GetString("SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Inicio.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Entrada.
        /// </summary>
        public static string StartJobDate {
            get {
                return ResourceManager.GetString("StartJobDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string StartSession {
            get {
                return ResourceManager.GetString("StartSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calle.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éxito.
        /// </summary>
        public static string Succes {
            get {
                return ResourceManager.GetString("Succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuerdo con Proveedor.
        /// </summary>
        public static string SupplierAgreement {
            get {
                return ResourceManager.GetString("SupplierAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.V.A..
        /// </summary>
        public static string Taxes {
            get {
                return ResourceManager.GetString("Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC.
        /// </summary>
        public static string TaxpayerId {
            get {
                return ResourceManager.GetString("TaxpayerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón Social.
        /// </summary>
        public static string TaxpayerName {
            get {
                return ResourceManager.GetString("TaxpayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string TaxRate {
            get {
                return ResourceManager.GetString("TaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        public static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direcciones.
        /// </summary>
        public static string Title_Address {
            get {
                return ResourceManager.GetString("Title_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mictlanix BE - Ramos Hermanos.
        /// </summary>
        public static string Title_Application {
            get {
                return ResourceManager.GetString("Title_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bancos.
        /// </summary>
        public static string Title_BankAccount {
            get {
                return ResourceManager.GetString("Title_BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cajas.
        /// </summary>
        public static string Title_CashDrawer {
            get {
                return ResourceManager.GetString("Title_CashDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Líneas de Producto.
        /// </summary>
        public static string Title_Category {
            get {
                return ResourceManager.GetString("Title_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Title_ChangePassword {
            get {
                return ResourceManager.GetString("Title_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre de Sesión.
        /// </summary>
        public static string Title_CloseSession {
            get {
                return ResourceManager.GetString("Title_CloseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactos.
        /// </summary>
        public static string Title_Contact {
            get {
                return ResourceManager.GetString("Title_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string Title_Customer {
            get {
                return ResourceManager.GetString("Title_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caja.
        /// </summary>
        public static string Title_CustomerPayment {
            get {
                return ResourceManager.GetString("Title_CustomerPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleados.
        /// </summary>
        public static string Title_Employee {
            get {
                return ResourceManager.GetString("Title_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mictlanix BE.
        /// </summary>
        public static string Title_Home {
            get {
                return ResourceManager.GetString("Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramos Hermanos.
        /// </summary>
        public static string Title_Logo {
            get {
                return ResourceManager.GetString("Title_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de Sesión.
        /// </summary>
        public static string Title_LogOn {
            get {
                return ResourceManager.GetString("Title_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta Nueva.
        /// </summary>
        public static string Title_NewSale {
            get {
                return ResourceManager.GetString("Title_NewSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntos de Venta.
        /// </summary>
        public static string Title_PointOfSale {
            get {
                return ResourceManager.GetString("Title_PointOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listas de Precios.
        /// </summary>
        public static string Title_PriceList {
            get {
                return ResourceManager.GetString("Title_PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string Title_Product {
            get {
                return ResourceManager.GetString("Title_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string Title_Register {
            get {
                return ResourceManager.GetString("Title_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventas.
        /// </summary>
        public static string Title_SalesOrder {
            get {
                return ResourceManager.GetString("Title_SalesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        public static string Title_Supplier {
            get {
                return ResourceManager.GetString("Title_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contratos.
        /// </summary>
        public static string Title_SupplierAgreement {
            get {
                return ResourceManager.GetString("Title_SupplierAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string Title_Users {
            get {
                return ResourceManager.GetString("Title_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacenes.
        /// </summary>
        public static string Title_Warehouse {
            get {
                return ResourceManager.GetString("Title_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Pago.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U. M..
        /// </summary>
        public static string UnitOfMeasurement {
            get {
                return ResourceManager.GetString("UnitOfMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Invalida.
        /// </summary>
        public static string Validation_Date {
            get {
                return ResourceManager.GetString("Validation_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} debe ser posterior a {1}..
        /// </summary>
        public static string Validation_DateGreaterThan {
            get {
                return ResourceManager.GetString("Validation_DateGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} contiene un valor duplicado..
        /// </summary>
        public static string Validation_Duplicate {
            get {
                return ResourceManager.GetString("Validation_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo introducido no corresponde a un {0}..
        /// </summary>
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario y/o contraseña son invalidos..
        /// </summary>
        public static string Validation_InvalidLogOn {
            get {
                return ResourceManager.GetString("Validation_InvalidLogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña actual es inválida..
        /// </summary>
        public static string Validation_InvalidPassword {
            get {
                return ResourceManager.GetString("Validation_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La nueva contraseña y la confirmación no coinciden..
        /// </summary>
        public static string Validation_PasswordDoNotMatch {
            get {
                return ResourceManager.GetString("Validation_PasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} es obligatorio..
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} es obligatorio y debe ser un número..
        /// </summary>
        public static string Validation_RequiredNumber {
            get {
                return ResourceManager.GetString("Validation_RequiredNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} debe tener entre {2} y {1} caracteres de largo..
        /// </summary>
        public static string Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo introducido no corresponde a un {0}..
        /// </summary>
        public static string Validation_Url {
            get {
                return ResourceManager.GetString("Validation_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitio Web.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferencia.
        /// </summary>
        public static string WireTransfer {
            get {
                return ResourceManager.GetString("WireTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Postal.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Zone {
            get {
                return ResourceManager.GetString("Zone", resourceCulture);
            }
        }
    }
}
