DELETE FROM inventory_issue_detail;
DELETE FROM inventory_issue;
DELETE FROM inventory_receipt_detail;
DELETE FROM inventory_receipt;
DELETE FROM inventory_transfer_detail;
DELETE FROM inventory_transfer;
DELETE FROM customer_payment;
DELETE FROM customer_refund_detail;
DELETE FROM customer_refund;
DELETE FROM fiscal_document_detail;
DELETE FROM fiscal_document_xml;
DELETE FROM fiscal_document;
DELETE FROM delivery_order_detail;
DELETE FROM delivery_order;
DELETE FROM sales_order_detail;
DELETE FROM sales_order;
DELETE FROM purchase_order_detail;
DELETE FROM purchase_order;

ALTER TABLE inventory_issue_detail AUTO_INCREMENT = 1;
ALTER TABLE inventory_issue AUTO_INCREMENT = 1;
ALTER TABLE inventory_receipt_detail AUTO_INCREMENT = 1;
ALTER TABLE inventory_receipt AUTO_INCREMENT = 1;
ALTER TABLE inventory_transfer_detail AUTO_INCREMENT = 1;
ALTER TABLE inventory_transfer AUTO_INCREMENT = 1;
ALTER TABLE customer_payment AUTO_INCREMENT = 1;
ALTER TABLE customer_refund_detail AUTO_INCREMENT = 1;
ALTER TABLE customer_refund AUTO_INCREMENT = 1;
ALTER TABLE fiscal_document_detail AUTO_INCREMENT = 1;
ALTER TABLE fiscal_document_xml AUTO_INCREMENT = 1;
ALTER TABLE fiscal_document AUTO_INCREMENT = 1;
ALTER TABLE sales_order_detail AUTO_INCREMENT = 1;
ALTER TABLE delivery_order AUTO_INCREMENT = 1;
ALTER TABLE sales_order_detail AUTO_INCREMENT = 1;
ALTER TABLE sales_order AUTO_INCREMENT = 1;
ALTER TABLE purchase_order_detail AUTO_INCREMENT = 1;
ALTER TABLE purchase_order AUTO_INCREMENT = 1;
