DELETE FROM inventory_issue_detail;
DELETE FROM inventory_issue;
DELETE FROM inventory_receipt_detail;
DELETE FROM inventory_receipt;
DELETE FROM inventory_transfer_detail;
DELETE FROM inventory_transfer;
DELETE FROM customer_payment;
DELETE FROM return_customer_detail;
DELETE FROM return_customer;
DELETE FROM sales_invoice_detail;
DELETE FROM sales_invoice;
DELETE FROM sales_order_detail;
DELETE FROM sales_order;
DELETE FROM purchase_order_detail;
DELETE FROM purchase_order;

ALTER TABLE inventory_issue_detail AUTO_INCREMENT = 1;
ALTER TABLE inventory_issue AUTO_INCREMENT = 1;
ALTER TABLE inventory_receipt_detail AUTO_INCREMENT = 1;
ALTER TABLE inventory_receipt AUTO_INCREMENT = 1;
ALTER TABLE inventory_transfer_detail AUTO_INCREMENT = 1;
ALTER TABLE inventory_transfer AUTO_INCREMENT = 1;
ALTER TABLE customer_payment AUTO_INCREMENT = 1;
ALTER TABLE return_customer_detail AUTO_INCREMENT = 1;
ALTER TABLE return_customer AUTO_INCREMENT = 1;
ALTER TABLE sales_invoice_detail AUTO_INCREMENT = 1;
ALTER TABLE sales_invoice AUTO_INCREMENT = 1;
ALTER TABLE sales_order_detail AUTO_INCREMENT = 1;
ALTER TABLE sales_order AUTO_INCREMENT = 1;
ALTER TABLE purchase_order_detail AUTO_INCREMENT = 1;
ALTER TABLE purchase_order AUTO_INCREMENT = 1;
